#!/bin/sh

if [ -z "$1" ]
then
    echo "Use the parameter --help to get info"
elif [ "$1" == "--help" ]
then
    echo "Usage: weather [LOCATION]"
    echo "The location shall be a city or province name for it to work"
else
    clear
    curl -s wttr.in/~${1}
    read
    clear
fi
