#!/bin/python

import sys

def addi(v1,v2):
    return int(v1) + int(v2)

def subt(v1,v2):
    return int(v1) - int(v2)

def mult(v1,v2):
    return int(v1) * int(v2)

def divi(v1,v2):
    return int(v1) // int(v2)

def main():
    if sys.argv[1] != "-n":
        if sys.argv[2] == "+":
            res = addi(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "-":
            res = subt(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "*":
            res = mult(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "/":
            res = divi(sys.argv[1], sys.argv[3])
            print(res)

    elif sys.argv[1] == "-n":
        if sys.argv[3] == "1":
            res = addi(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "2":
            res = subt(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "3":
            res = mult(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "4":
            res = divi(sys.argv[2], sys.argv[4])
            print(res)

if __name__ == "__main__":
    main()
