#!/bin/sh

if [ -z "${1}" ]
then
    echo "Use the parameter --help to get help"
elif [ "${1}" == "--help" ]
then
    echo "Valid expressions are INTEGER OPERATOR INTEGER like 2 + 2"
    echo "Expressions can also have multiple operators and more integers like 2 + 2 - 1"
else
    res=$((${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}))
    echo "${res}"
fi
