#!/bin/python

import sys

def noargs():
    print("[calc] No arguments passed, use the -h or --help switch for a list of options")
    return

def help():
    print("[calc] Usage: calc [OPTIONS] [INTEGER] [OPERATOR] [INTEGER]")
    print("[calc] List of switches:")
    print("    -h or --help ## Shows you this")
    print("    -n ## Switch to program/number operator mode")
    print("\n[calc] List of operators:")
    print("Note that number operators are only available when using the -n switch")
    print("    + or 1 ## Addition")
    print("    - or 2 ## Substraction")
    print("    \* or 3 ## Multiplication")
    print("    / or 4 ## Division")
    return

def addi(v1,v2): # Add the numbers v1 and v2
    return int(v1) + int(v2)

def subt(v1,v2): # Subtract the numbers v2 from v1
    return int(v1) - int(v2)

def mult(v1,v2): # Multiply the numbers v1 and v2
    return int(v1) * int(v2)

def divi(v1,v2): # Divide the numbers v1 by v2
    return int(v1) // int(v2)

def expo(v1,v2): # Raise v1 to the power of v2
    return int(v1) ** int(v2)

def main():
    if len(sys.argv) < 2: # Check if any args are provided
        noargs() # Show the player some info

    elif sys.argv[1] == "-h" or sys.argv[1] == "--help": # Check for a help switch
        help() # Show the help text

    elif sys.argv[1] != "-n": # Regular operator mode
        if sys.argv[2] == "+":
            res = addi(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "-":
            res = subt(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "*":
            res = mult(sys.argv[1], sys.argv[3])
            print(res)
        elif sys.argv[2] == "/":
            res = divi(sys.argv[1], sys.argv[3])
            print(res)

    elif sys.argv[1] == "-n": # Program/Number operator mode
        if sys.argv[3] == "1":
            res = addi(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "2":
            res = subt(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "3":
            res = mult(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "4":
            res = divi(sys.argv[2], sys.argv[4])
            print(res)
        elif sys.argv[3] == "5":
            res = expo(sys.argv[2], sys.argv[4])
            print(res)

if __name__ == "__main__":
    main()
