#!/bin/python

import sys
import requests

if len(sys.argv) < 2:
    print("[trackip] No arguments passed, append --help or -h for a list of switches")
elif sys.argv[1] == "-h" or sys.argv[1] == "--help":
    print("[trackip] -h / --help # Shows you this\n[trackip] Usage: trackip [IPADDR]")
else:
    r = requests.get("http://ipinfo.io/" + sys.argv[1])
    data = r.json()
    print("IP: " + data["ip"])
    print("Hostname: " + data["hostname"])
    print("City: " + data["city"])
    print("Region: " + data["region"])
    print("Country: " + data["country"])
    print("Coordinates: " + data["loc"])
    print("Organization: " + data["org"])
    print("Postal Code: " + data["postal"])
