#!/bin/python

import os
import sys
import requests
import json

if len(sys.argv) < 2:
    print("[trackip] No arguments passed, append --help or -h for a list of switches")
elif sys.argv[1] == "-h" or sys.argv[1] == "--help":
    print("[trackip] -h / --help # Shows you this\n[trackip] Usage: trackip [IPADDR]")
else:
    r = requests.get('http://ipinfo.io/' + sys.argv[1])
    print(r.json())
