#!/bin/sh

USER1=archie

if [[ $(whoami) != "root" ]]
    then echo "Run as root"
    exit 1
fi

if [ "$(ls /bin | grep trizen)" == "trizen" ]
then
    PKGMAN=trizen
else
    PKGMAN=pacman
fi

checkoptional ()
{
    if [ "$1" == "--help" ]
    then
        echo "Parameters:"
        echo "--help ## Shows you this"
        echo "--pacclear ## Clear the pacman cache except for currently installed packages"
    fi

    elif [ "$1" == "--all" ]
    then
        ${PKGMAN} -Sc
        rm -r /root/.cache/*
        rm -r /home/${USER1}/.cache/*
    fi
}

echo "Cleaning..."
paccache -ruk0
paccache -rk 2
checkoptional
echo "Done!"
